#!/bin/bash

SERVER_TIME=$(date)
UPTIME=$(uptime -p)
DISK_USAGE=$(df -h / | awk 'NR==2 {print $5 " used of " $2}')
MEMORY_USAGE=$(free -h | awk '/Mem:/ {print $3 " used of " $2}')
NGINX_STATUS=$(systemctl is-active nginx)
PUBLIC_IP="15.134.211.37"

cat > /var/www/html/status.html <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Server Status - ICT171 Cloud Project</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background: #f4f7fb;
            color: #222;
        }

        header {
            background: linear-gradient(135deg, #1f3b73, #2f80ed);
            color: white;
            padding: 45px 20px;
            text-align: center;
        }

        nav {
            background: #16213e;
            padding: 15px;
            text-align: center;
        }

        nav a {
            color: white;
            text-decoration: none;
            margin: 0 15px;
            font-weight: bold;
        }

        section {
            max-width: 900px;
            margin: 35px auto;
            background: white;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 3px 12px rgba(0,0,0,0.08);
        }

        h2 {
            color: #1f3b73;
            border-bottom: 2px solid #2f80ed;
            padding-bottom: 8px;
        }

        .status-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
            gap: 20px;
        }

        .card {
            background: #eef4ff;
            padding: 20px;
            border-radius: 10px;
            border-left: 5px solid #2f80ed;
        }

        .card h3 {
            margin-top: 0;
            color: #1f3b73;
        }

        footer {
            text-align: center;
            background: #16213e;
            color: white;
            padding: 20px;
            margin-top: 40px;
        }
    </style>
</head>
<body>

<header>
    <h1>ICT171 Server Status Dashboard</h1>
    <p>Automatically generated by a Bash script on the EC2 server</p>
</header>

<nav>
    <a href="index.html">Home</a>
    <a href="status.html">Server Status</a>
</nav>

<section>
    <h2>Live Server Status</h2>

    <div class="status-grid">
        <div class="card">
            <h3>Server Time</h3>
            <p>$SERVER_TIME</p>
        </div>

        <div class="card">
            <h3>Server Uptime</h3>
            <p>$UPTIME</p>
        </div>

        <div class="card">
            <h3>Disk Usage</h3>
            <p>$DISK_USAGE</p>
        </div>

        <div class="card">
            <h3>Memory Usage</h3>
            <p>$MEMORY_USAGE</p>
        </div>

        <div class="card">
            <h3>Nginx Status</h3>
            <p>$NGINX_STATUS</p>
        </div>

        <div class="card">
            <h3>Public IPv4 Address</h3>
            <p>$PUBLIC_IP</p>
        </div>
    </div>
</section>

<footer>
    <p>ICT171 Cloud Server Project | Script-generated server report</p>
</footer>

</body>
</html>
HTML
